### ISSUE TITLE
Attention: the file 'src/base/fftw3.f90' depends on 'fftw3.f03' that is unreachable

### ISSUE THREAD

**Issue by xpingg** [tanner-trickle/EXCEED-DM#3] opened 2021-08-25 15:25 UTC
Hi,

I'm trying to install EXCEED-DM on fresh Ubuntu 18.04, and i'm sure i've installed all the preliminary software,but when i tried to build this by 

FoBiS.py build -mode ubuntu-gnu

it always warns me that

Attention: the file 'src/base/fftw3.f90' depends on 'fftw3.f03' that is unreachable

but the file 'fftw3.f03' is exactly in the right place:'/usr/include'

Could you help me solve this issue?

Thanks!

**Comment by xpingg** [comment] 2021-08-25 15:31
I move the 'fftw3.f03' to src/base/fftw3.f90 and the issue fixed.

**Comment by tanner-trickle** [comment] 2021-08-25 17:26
Hi @xpingg! This is a known issue when building the software with FoBiS.py. The fftw3.f90 file directly references the fftw3.f03 file via an include statement (see more here: https://fftw.org/doc/Defining-an-FFTW-module.html). When building, FoBiS.py searches the source directory for this file (as it does for the other modules), and then raises this 'Attention:' message when it doesn't find fftw3.f03 in the source directory (which is why the issue is fixed once you move the file in to the source directory). However this does not seem to affect the final build, since FFTW3 is later linked through specific paths.

If fftw3.f03 is in /usr/include, and the libfftw3.* files are in /usr/lib/x86_64-linux-gnu (the default include and library directories for Ubuntu 18.04), and the program successfully builds then everything should be working!

I would recommend that you leave the fftw3.f03 file in the /usr/include directory and ignore that specific  'Attention:' message.

Hope this helps!

**Comment by xpingg** [comment] 2021-08-26 00:55
Thanks for the reply!
I'm sorry I made a mistake actually I copy the  fftw3.f03 to src/base rather than move it.
And it can pass the building with the Warning like you said.

**Closed as completed** 2021-08-26 00:57 UTC
Labels: FoBiS
